#!/usr/bin/env perl

# Copyright (c) 2022-2023 Thomas Frohwein
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;
use v5.32;
use version 0.77; our $VERSION = version->declare('v0.0.1');

use FindBin; use lib "$FindBin::Bin/../lib";

use IndieRunner;
use IndieRunner::Cmdline;

my %cli_config = %{ IndieRunner::Cmdline::init_cli() };
chdir $cli_config{ dir } or die "Failed to enter $cli_config{ dir }: $!";

my $indierunner = IndieRunner->new( %cli_config );
$indierunner->setup();
$indierunner->run();
$indierunner->finish();

__END__

=head1 NAME

indierunner - command-line interface to IndieRunner

=head1 SYNOPSIS

indierunner [-hnmsvV] [-d I<dir>] [-D I<dllmap>] [-f I<file>] [-g I<game>] [-e I<engine>] [-- I<game arguments>]

=head1 OPTIONS

=over 8

=item B<--directory=I<directory>/-d I<directory>>

Switch to I<directory>.

=item B<--dryrun/-n>

Show actions that would be taken, without changing or executing anything.

=item B<--dllmap=I<file>/-D I<file>>

For use with Mono/FNA/XNA only: specify custom I<file> with dllmap assignments.

=item B<--engine=I<engine>/-e I<engine>>

Bypass automatic engine detection. Use with caution.

=item B<--file=I<file>/-f I<file>>

Specify the main game file and bypass autodetection.

=item B<--game=I<game>/-g I<game>>

Bypass automatic game detection and run as I<game>. Use with caution.

=item B<--help/-h>

Print a brief help message.

=item B<--man/-m>

Print the manual page and exits.

=item B<--script/-s>

Instead of launching the game, generate a shell script to take all the steps (experimental).

=item B<--usage>

Print short usage information.

=item B<--verbose/-v>

Enable verbose output.

=item B<--version/-V>

Print version.

=item B<-- I<game arguments>>

Arguments to pass to the invocation of the game itself, like: C<-windowed -skipintro>

=back

=head1 DESCRIPTION

B<indierunner> is the reference CLI frontend for the IndieRunner module. 

=head1 SEE ALSO

L<IndieRunner>

=head1 AUTHOR

Thomas Frohwein
