#!/usr/bin/perl

# Copyright (c) 2022 Thomas Frohwein
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;
use v5.32;
use version 0.77; our $VERSION = version->declare('v0.0.1');

use FindBin; use lib "$FindBin::Bin/../lib";

use IndieRunner;

####################################
### Outline for future structure ###
####################################

### 1. Get Initial Data ###

# CLI args, esp. dryrun & verbose & engine & main_game_file
# Engine Name
# Game Name
# set OS-specific commands (for dryrun output)

### 2. Setup of Files (incl. Symlinks) ###

# fork & exec; pledge & unveil

### 3. Assemble Configuration of Runtime ###

# by general engine configuration, game-specific config, and user-provided
# elements: environment, binary, arguments, potentially symlinks
# get unveil paths
# get engine-specific pledge promises

### 4. Fork + Exec Runtime (unless dryrun) ###

# with unveil + pledge as appropriate
